const data = [
  {
    id: 245461,
    imageType: 'jpg',
    title: 'African Chicken Peanut Stew',
    readyInMinutes: 120,
    servings: 6,
    sourceUrl: 'http://www.simplyrecipes.com/recipes/african_chicken_peanut_stew/',
  },
  {
    id: 975759,
    imageType: 'jpg',
    title: 'African Chicken Peanut Stew',
    readyInMinutes: 135,
    servings: 6,
    sourceUrl: 'https://www.simplyrecipes.com/recipes/african_chicken_peanut_stew/',
  },
  {
    id: 163315,
    imageType: 'jpg',
    title: 'West African Peanut-Chicken Stew',
    readyInMinutes: 50,
    servings: 5,
    sourceUrl:
      'http://www.BettyCrocker.com/recipes/west-african-peanut-chicken-stew/d66ab29e-fbee-45d7-80c6-8341dc49c42b',
  },
  {
    id: 479680,
    imageType: 'jpg',
    title: 'Vegetarian African Peanut Stew',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://feedmephoebe.com/2012/01/vegetarian-african-peanut-stew/',
  },
  {
    id: 709380,
    imageType: 'jpg',
    title: 'West African Peanut Stew',
    readyInMinutes: 45,
    servings: 5,
    sourceUrl: 'http://www.curiouscuisiniere.com/african-peanut-stew/',
  },
  {
    id: 854978,
    imageType: 'jpg',
    title: 'One-Pot African Peanut Stew',
    readyInMinutes: 60,
    servings: 6,
    sourceUrl: 'http://makingthymeforhealth.com/one-pot-african-peanut-stew/',
  },
  {
    id: 612559,
    imageType: 'jpg',
    title: 'African Peanut Stew (vegan)',
    readyInMinutes: 55,
    servings: 6,
    sourceUrl: 'http://www.budgetbytes.com/2014/08/african-peanut-stew-vegan/',
  },
  {
    id: 35648,
    imageType: 'jpg',
    title: 'Vegetarian African Peanut Stew',
    readyInMinutes: 30,
    servings: 4,
    sourceUrl: 'http://www.biggirlssmallkitchen.com/2011/12/vegetarian-african-peanut-stew.html',
  },
  {
    id: 1625083,
    imageType: 'jpg',
    title: 'West African Peanut Stew',
    readyInMinutes: 45,
    servings: 8,
    sourceUrl: 'https://ethnicspoon.com/west-african-peanut-stew/',
  },
  {
    id: 34797,
    imageType: 'jpg',
    title: 'West African Vegetable And Peanut Stew',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.eat-drink-smile.com/2010/01/meatless-monday-african-stew.html',
  },
  {
    id: 35780,
    imageType: 'jpg',
    title: 'African Peanut Stew With Shrimp And Butternut Squash',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'http://feedmephoebe.com/2012/12/feeding-friends-african-peanut-stew-with-shrimp-and-butternut-squash/',
  },
  {
    id: 1187177,
    imageType: 'jpg',
    title: 'West African Peanut Stew with Sweet Potato & Spinach',
    readyInMinutes: 35,
    servings: 4,
    sourceUrl: 'https://www.kitchentreaty.com/west-african-peanut-stew/',
  },
  {
    id: 412225,
    imageType: 'jpg',
    title: 'West African Chicken Stew',
    readyInMinutes: 50,
    servings: 8,
    sourceUrl: 'http://www.tasteofhome.com/Recipes/west-african-chicken-stew',
  },
  {
    id: 125739,
    imageType: 'jpg',
    title: 'North African Chicken Stew',
    readyInMinutes: 30,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/north-african-chicken-stew-428359',
  },
  {
    id: 550772,
    imageType: 'jpg',
    title: 'West African Chicken Stew – A Right Out of Well Fed 2',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: 'http://thehealthyfoodie.com/west-african-chicken-stew-well-fed-2/',
  },
  {
    id: 779804,
    imageType: 'jpg',
    title: 'African Sweet Potato & Chicken Stew',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.eatingwell.com/recipes/african_sweet_potato_chicken_stew.html',
  },
  {
    id: 575018,
    imageType: 'jpg',
    title:
      'Quick and Easy African Pork Peanut Stew, by Pork Passion Pursuit Winner Devon Delaney (Sponsored)',
    readyInMinutes: 40,
    servings: 6,
    sourceUrl: 'http://www.theculinarylife.com/2014/african-pork-peanut-stew-pork-passion-pursuit/',
  },
  {
    id: 563530,
    imageType: 'jpg',
    title: 'African Groundnut Chicken and Sweet Potato Stew',
    readyInMinutes: 30,
    servings: 4,
    sourceUrl: 'http://www.godairyfree.org/recipes/african-chicken-and-sweet-potato-stew',
  },
  {
    id: 172600,
    imageType: 'jpg',
    title: 'Slow-Cooker African Groundnut Stew with Chicken',
    readyInMinutes: 500,
    servings: 8,
    sourceUrl:
      'http://www.bettycrocker.com/recipes/slow-cooker-african-groundnut-stew-with-chicken/54116a3f-8966-4ccc-9454-c067b4e2a195',
  },
  {
    id: 239068,
    imageType: 'jpg',
    title: 'West African Peanut Chicken',
    readyInMinutes: 40,
    servings: 4,
    sourceUrl: 'http://www.myrecipes.com/m/recipe/west-african-peanut-chicken-10000001940154/',
  },
  {
    id: 570458,
    imageType: 'jpg',
    title: 'African Potato and Cauliflower Stew',
    readyInMinutes: 40,
    servings: 6,
    sourceUrl:
      'http://shescookin.com/2014/03/09/potatoes-around-the-world-african-potato-and-cauliflower-stew/',
  },
  {
    id: 22623,
    imageType: 'jpg',
    title: 'North African Vegetable Stew',
    readyInMinutes: 40,
    servings: 1,
    sourceUrl: 'http://norecipes.com/blog/2008/08/28/north-african-stewed-veggies/',
  },
  {
    id: 377946,
    imageType: 'jpg',
    title: 'West African Beef Stew',
    readyInMinutes: 80,
    servings: 6,
    sourceUrl: 'http://www.tasteofhome.com/Recipes/west-african-beef-stew',
  },
  {
    id: 15888,
    imageType: 'jpg',
    title: 'North African Lamb Stew',
    readyInMinutes: 98,
    servings: 4,
    sourceUrl: 'http://www.myrecipes.com/recipe/north-african-lamb-stew-00420000003554/',
  },
  {
    id: 172593,
    imageType: 'jpg',
    title: 'African Squash and Chickpea Stew',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'http://www.bettycrocker.com/recipes/african-squash-and-chick-pea-stew/77eeecfb-8fcc-4b33-8387-3289b3dea74d',
  },
  {
    id: 208194,
    imageType: 'jpg',
    title: 'Healthy & Delicious: West African Vegetable Stew',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.seriouseats.com/recipes/2010/05/west-african-vegetable-stew-recipe.html',
  },
  {
    id: 707902,
    imageType: 'jpg',
    title: 'West African Beef, Plantain, and Okra Stew',
    readyInMinutes: 85,
    servings: 8,
    sourceUrl: 'http://www.myrecipes.com/recipe/beef-plantain-okra-stew-50400000137551/',
  },
  {
    id: 280666,
    imageType: 'jpg',
    title: 'African Ground Nut Stew with Sour Cream-Chive Topping',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      'http://www.myrecipes.com/recipe/african-ground-nut-stew-with-sour-cream-chive-topping-10000001611661/',
  },
  {
    id: 495056,
    imageType: 'jpg',
    title: 'African Peanut Soup',
    readyInMinutes: 30,
    servings: 8,
    sourceUrl: 'http://ohmyveggies.com/african-peanut-soup/',
  },
  {
    id: 35610,
    imageType: 'jpg',
    title: 'African Peanut Soup',
    readyInMinutes: 10,
    servings: 6,
    sourceUrl: 'http://www.myrecipes.com/recipe/african-peanut-soup-10000001094006/',
  },
  {
    id: 697070,
    imageType: 'jpg',
    title: 'African Peanut Soup',
    readyInMinutes: 20,
    servings: 4,
    sourceUrl: 'http://www.eatingwell.com/recipes/african_peanut_soup.html',
  },
  {
    id: 494465,
    imageType: 'jpg',
    title: 'Sweetpotato African Peanut Soup',
    readyInMinutes: 40,
    servings: 6,
    sourceUrl: 'http://www.curiouscuisiniere.com/sweet-potato-african-peanut-soup/',
  },
  {
    id: 527128,
    imageType: 'jpg',
    title: 'West African Peanut Soup',
    readyInMinutes: 45,
    servings: 5,
    sourceUrl: 'http://www.gimmesomeoven.com/west-african-peanut-soup/',
  },
  {
    id: 107726,
    imageType: 'jpg',
    title: 'Spicy African Peanut Soup',
    readyInMinutes: 30,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/spicy-african-peanut-soup-24464',
  },
  {
    id: 46362,
    imageType: 'jpg',
    title: 'African Peanut And Yam Soup',
    readyInMinutes: 40,
    servings: 4,
    sourceUrl:
      'http://thewellseasonedcook.blogspot.com/2008/08/african-peanut-and-yam-soup-my-legume.html',
  },
  {
    id: 978429,
    imageType: 'jpg',
    title: 'Mary’s African Peanut Soup',
    readyInMinutes: 45,
    servings: 5,
    sourceUrl: 'https://fountainavenuekitchen.com/african-peanut-soup/',
  },
  {
    id: 925381,
    imageType: 'jpg',
    title: 'West African Peanut Soup',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://cookieandkate.com/2013/west-african-peanut-soup/',
  },
  {
    id: 107519,
    imageType: 'jpg',
    title: 'West African Peanut Soup',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.food.com/recipe/west-african-peanut-soup-134219',
  },
  {
    id: 1608565,
    imageType: 'jpg',
    title: 'African Peanut Soup – Our veggie take on a classic',
    readyInMinutes: 25,
    servings: 3,
    sourceUrl: 'https://hurrythefoodup.com/african-peanut-soup/',
  },
  {
    id: 684963,
    imageType: 'jpg',
    title: 'African Peanut Soup with Sweet Potatoes',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.curiouscuisiniere.com/african-peanut-soup/',
  },
  {
    id: 1599909,
    imageType: 'jpg',
    title: 'West African Peanut Soup - Not Enough Cinnamon',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'https://www.notenoughcinnamon.com/west-african-peanut-soup/',
  },
  {
    id: 93984,
    imageType: 'jpg',
    title: 'African Sweet Potato and Peanut Soup',
    readyInMinutes: 30,
    servings: 3,
    sourceUrl: 'http://www.food.com/recipe/african-sweet-potato-and-peanut-soup-252532',
  },
  {
    id: 100227,
    imageType: 'jpg',
    title: 'Spicy African Peanut Soup With Chickpeas',
    readyInMinutes: 35,
    servings: 10,
    sourceUrl: 'http://www.food.com/recipe/spicy-african-peanut-soup-with-chickpeas-339766',
  },
  {
    id: 45027,
    imageType: 'jpg',
    title: 'Baked Sweet Potatoes with West African-Style Peanut Sauce',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      'http://www.myrecipes.com/recipe/baked-sweet-potatoes-with-west-african-style-peanut-sauce-10000001536675/',
  },
  {
    id: 35414,
    imageType: 'jpg',
    title: 'Chicken and Peanut Stew',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.foodandwine.com/recipes/chicken-and-peanut-stew',
  },
  {
    id: 660221,
    imageType: 'jpg',
    title: 'Skinny Chicken Peanut Stew',
    readyInMinutes: 60,
    servings: 4,
    sourceUrl: 'https://spoonacular.com/skinny-chicken-peanut-stew-660221',
  },
  {
    id: 542132,
    imageType: 'jpg',
    title: 'PEANUT STEW WITH CHICKEN from Ghana',
    readyInMinutes: 90,
    servings: 6,
    sourceUrl: 'http://www.panningtheglobe.com/2012/10/29/peanut-stew-with-chicken-from-ghana/',
  },
  {
    id: 136481,
    imageType: 'jpg',
    title: 'North African Chicken',
    readyInMinutes: 25,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/north-african-chicken-373000',
  },
  {
    id: 559156,
    imageType: 'jpg',
    title: 'East African Braised Chicken',
    readyInMinutes: 105,
    servings: 4,
    sourceUrl:
      'http://www.jocooks.com/main-courses/poultry-main-courses/east-african-braised-chicken/',
  },
  {
    id: 1116214,
    imageType: 'jpg',
    title: 'South African Chutney Chicken',
    readyInMinutes: 105,
    servings: 6,
    sourceUrl: 'https://www.curiouscuisiniere.com/chutney-chicken/',
  },
  {
    id: 56798,
    imageType: 'jpg',
    title: 'East African Braised Chicken',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.myrecipes.com/recipe/east-african-braised-chicken-10000000226728/',
  },
  {
    id: 1094081,
    imageType: 'jpg',
    title: 'South African chutney chicken',
    readyInMinutes: 55,
    servings: 4,
    sourceUrl: 'https://www.bbcgoodfood.com/recipes/south-african-chutney-chicken',
  },
  {
    id: 142981,
    imageType: 'jpg',
    title: 'South African Orange Chicken',
    readyInMinutes: 85,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/south-african-orange-chicken-129125',
  },
  {
    id: 81046,
    imageType: 'jpg',
    title: 'African Style Chicken Salad',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: 'http://www.health-bent.com/proteins/african-style-chicken-salad',
  },
  {
    id: 374273,
    imageType: 'jpg',
    title: 'African Chicken & Sweet Potatoes',
    readyInMinutes: 50,
    servings: 6,
    sourceUrl: 'http://www.tasteofhome.com/recipes/african-chicken---sweet-potatoes',
  },
  {
    id: 119610,
    imageType: 'jpg',
    title: 'African Chicken in Spicy Red Sauce',
    readyInMinutes: 90,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/african-chicken-in-spicy-red-sauce-229398',
  },
  {
    id: 112385,
    imageType: 'jpg',
    title: 'African Chicken in Spicy Red Sauce',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.myrecipes.com/recipe/african-chicken-spicy-red-sauce-10000001536760/',
  },
  {
    id: 542178,
    imageType: 'jpg',
    title: 'COCONUT CHICKEN with East African Flavors',
    readyInMinutes: 75,
    servings: 5,
    sourceUrl:
      'http://www.panningtheglobe.com/2012/12/10/coconut-chicken-with-east-african-flavors/',
  },
  {
    id: 269428,
    imageType: 'jpg',
    title: 'Slow-Cooked South African BBQ Chicken',
    readyInMinutes: 495,
    servings: 15,
    sourceUrl:
      'http://www.Kraftrecipes.com/recipes/slow-cooked-south-african-bbq-chicken-125056.aspx',
  },
  {
    id: 704612,
    imageType: 'jpg',
    title: 'Kuku Paku (African Coconut Chicken Curry)',
    readyInMinutes: 35,
    servings: 3,
    sourceUrl: 'http://www.curiouscuisiniere.com/african-coconut-chicken-curry/',
  },
  {
    id: 122712,
    imageType: 'jpg',
    title: 'North African Quick Tagine-Style Chicken',
    readyInMinutes: 35,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/north-african-quick-tagine-style-chicken-229388',
  },
  {
    id: 314135,
    imageType: 'jpeg',
    title: 'North African Inspired Rub for Fish and Chicken',
    readyInMinutes: 14,
    servings: 4,
    sourceUrl:
      'http://www.foodnetwork.com/recipes/bobby-flay/north-african-inspired-rub-for-fish-and-chicken-recipe.html',
  },
  {
    id: 149671,
    imageType: 'jpg',
    title: 'Grilled Chicken Breasts with North African Spice Paste',
    readyInMinutes: 50,
    servings: 4,
    sourceUrl:
      'http://www.epicurious.com/recipes/food/views/Grilled-Chicken-Breasts-with-North-African-Spice-Paste-238692',
  },
  {
    id: 759837,
    imageType: 'jpg',
    title: 'Spicy Peanut Stew',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.vegetariantimes.com/recipe/spicy-peanut-stew/',
  },
  {
    id: 598286,
    imageType: 'jpg',
    title: 'Peanut Stew with Turkey',
    readyInMinutes: 75,
    servings: 4,
    sourceUrl: 'http://leitesculinaria.com/11808/recipes-african-peanut-stew.html',
  },
  {
    id: 962580,
    imageType: 'jpg',
    title: 'Sweet Potato Peanut Stew',
    readyInMinutes: 35,
    servings: 6,
    sourceUrl: 'https://runningonrealfood.com/sweet-potato-peanut-stew/',
  },
  {
    id: 35755,
    imageType: 'jpg',
    title: 'Peanut Stew With Sweet Potatoes And Spinach',
    readyInMinutes: 25,
    servings: 2,
    sourceUrl: 'http://naturallyella.com/2012/02/24/peanut-stew-with-sweet-potatoes-and-spinach/',
  },
  {
    id: 1430607,
    imageType: 'jpg',
    title: 'Vegan Sweet Potato Peanut Stew',
    readyInMinutes: 35,
    servings: 6,
    sourceUrl: 'https://runningonrealfood.com/vegan-sweet-potato-peanut-stew/',
  },
  {
    id: 686957,
    imageType: 'jpg',
    title: 'Peanut Stew with Sweet Potatoes and Spinach',
    readyInMinutes: 35,
    servings: 2,
    sourceUrl: 'http://naturallyella.com/peanut-stew-with-sweet-potatoes-and-spinach/',
  },
  {
    id: 628277,
    imageType: 'jpg',
    title: 'Vegan Sweet Potato Peanut Stew',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.mountainmamacooks.com/2015/02/sweet-potato-peanut-stew/',
  },
  {
    id: 830990,
    imageType: 'jpg',
    title: 'Spicy Peanut Stew with Rice and Chickpeas',
    readyInMinutes: 25,
    servings: 8,
    sourceUrl: 'http://runningonrealfood.com/vegan-spicy-peanut-stew/',
  },
  {
    id: 619186,
    imageType: 'jpg',
    title: 'Low Carb Pumpkin, Pork and Peanut Stew',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      'http://www.ibreatheimhungry.com/2014/10/pumpkin-pork-peanut-stew-low-carb-gluten-free.html',
  },
  {
    id: 223723,
    imageType: 'jpg',
    title: 'Slow-Cooker Peanut-Sweet Potato Stew',
    readyInMinutes: 320,
    servings: 4,
    sourceUrl:
      'http://www.myrecipes.com/recipe/slow-cooker-peanut-sweet-potato-stew-10000001924646/',
  },
  {
    id: 112643,
    imageType: 'jpg',
    title: 'Nigerian Kidney Bean Stew With a Peanut Sauce',
    readyInMinutes: 200,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/nigerian-kidney-bean-stew-with-a-peanut-sauce-290843',
  },
  {
    id: 103944,
    imageType: 'jpg',
    title: 'KARI-KARE (Meat and Vegetable Stew in Peanut Sauce)',
    readyInMinutes: 135,
    servings: 6,
    sourceUrl: 'http://www.food.com/recipe/kari-kare-meat-and-vegetable-stew-in-peanut-sauce-14626',
  },
  {
    id: 506917,
    imageType: 'jpg',
    title: 'South African Piri-Piri Chicken',
    readyInMinutes: 210,
    servings: 4,
    sourceUrl: 'http://thewanderlustkitchen.com/2014/04/04/south-african-piri-piri-chicken-2/',
  },
  {
    id: 470413,
    imageType: 'jpg',
    title: 'African Curry',
    readyInMinutes: 60,
    servings: 4,
    sourceUrl: 'http://allrecipes.com/Recipe/African-Curry/Detail.aspx?src=rss',
  },
  {
    id: 88823,
    imageType: 'jpg',
    title: 'African Tilapia',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/african-tilapia-127166',
  },
  {
    id: 113161,
    imageType: 'jpg',
    title: 'African Gumbo',
    readyInMinutes: 80,
    servings: 4,
    sourceUrl: 'http://www.food.com/recipe/african-gumbo-238377',
  },
  {
    id: 125438,
    imageType: 'jpg',
    title: 'East African Curry',
    readyInMinutes: 40,
    servings: 6,
    sourceUrl: 'http://www.food.com/recipe/east-african-curry-310179',
  },
  {
    id: 109279,
    imageType: 'jpg',
    title: 'African Style Broccoli',
    readyInMinutes: 15,
    servings: 6,
    sourceUrl: 'http://www.food.com/recipe/african-style-broccoli-141308',
  },
  {
    id: 124092,
    imageType: 'jpg',
    title: 'South African Pudding',
    readyInMinutes: 60,
    servings: 6,
    sourceUrl: 'http://www.food.com/recipe/south-african-pudding-140189',
  },
  {
    id: 181340,
    imageType: 'jpg',
    title: 'African Squash and Yams',
    readyInMinutes: 30,
    servings: 6,
    sourceUrl:
      'http://www.BettyCrocker.com/recipes/african-squash-and-yams/c488eaa6-9816-4b8c-bb6a-d04f4d10d3a8/reviews',
  },
  {
    id: 14769,
    imageType: 'jpg',
    title: 'West African Poussain',
    readyInMinutes: 95,
    servings: 6,
    sourceUrl: 'http://www.cuisinart.com/recipes/entrees/4281.html',
  },
  {
    id: 122715,
    imageType: 'jpg',
    title: 'African Mango Fool',
    readyInMinutes: 20,
    servings: 2,
    sourceUrl: 'http://www.food.com/recipe/african-mango-fool-171625',
  },
  {
    id: 493499,
    imageType: 'jpg',
    title: 'East-African Spritz',
    readyInMinutes: 15,
    servings: 4,
    sourceUrl: 'http://www.foodrepublic.com/2012/03/31/east-african-spritz-recipe',
  },
  {
    id: 632003,
    imageType: 'jpg',
    title: 'African Bean Soup',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://spoonacular.com/african-bean-soup-632003',
  },
  {
    id: 30806,
    imageType: 'jpg',
    title: 'African Veg Curry',
    readyInMinutes: 30,
    servings: 4,
    sourceUrl: 'http://naturallyella.com/2010/02/10/african-veg-curry/',
  },
  {
    id: 384740,
    imageType: 'jpg',
    title: 'African Beef Curry',
    readyInMinutes: 105,
    servings: 4,
    sourceUrl: 'http://www.tasteofhome.com/Recipes/african-beef-curry',
  },
  {
    id: 107157,
    imageType: 'jpg',
    title: 'African Hot Sauce',
    readyInMinutes: 65,
    servings: 1,
    sourceUrl: 'http://www.food.com/recipe/african-hot-sauce-172781',
  },
  {
    id: 306409,
    imageType: 'jpeg',
    title: 'North African Meatballs',
    readyInMinutes: 70,
    servings: 4,
    sourceUrl:
      'http://www.foodnetwork.com/recipes/melissa-darabian/north-african-meatballs-recipe.html',
  },
  {
    id: 771344,
    imageType: 'jpeg',
    title: 'South African Sambal',
    readyInMinutes: 195,
    servings: 1,
    sourceUrl: 'http://www.foodnetwork.com/recipes/south-african-sambal-recipe.html',
  },
  {
    id: 52281,
    imageType: 'jpg',
    title: 'Kare Kare (ox Tail And Peanut Stew) Recipe',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://rasamalaysia.com/filipino-kare-kare-ox-tail-and-peanut-stew/2/',
  },
  {
    id: 101246,
    imageType: 'jpg',
    title: 'North African Soup (Vegetarian)',
    readyInMinutes: 75,
    servings: 2,
    sourceUrl: 'http://www.food.com/recipe/north-african-soup-vegetarian-385621',
  },
];

data.forEach((x) => {
  console.log(x.id);
});
